import AppKit

/// The Locus fish in the menu bar: plain when idle, with a red alert badge during a session.
///
/// The fish keeps the logo's original colors (PRD-0006), so it is not a template image.
/// It lives in `Support/MenuBar` (generated by `scripts/make-menubar-icon.swift`),
/// and `build-app.sh` copies it into the bundle.
/// Without the bundle (e.g. `swift run`) it falls back to SF Symbol padlocks.
enum MenuBarIcon {
    private static let fish: NSImage? = Bundle.main.image(forResource: "MenuBarIcon")

    static let idle: NSImage? = fish ?? symbol("lock.open")

    static let inSession: NSImage? = fish.map(badged) ?? symbol("lock.fill")

    /// The fish with a red "!" badge at its top-right, cut out of the fish so it stays legible.
    /// The canvas grows up and right so the badge mostly sits outside the fish and leaves the eye visible.
    private static func badged(_ fish: NSImage) -> NSImage {
        let diameter: CGFloat = 8.5
        let overhang: CGFloat = 4
        let size = NSSize(width: fish.size.width + overhang, height: fish.size.height + overhang)
        let image = NSImage(size: size, flipped: false) { rect in
            fish.draw(in: NSRect(origin: .zero, size: fish.size))

            let badge = NSRect(x: rect.maxX - diameter, y: rect.maxY - diameter, width: diameter, height: diameter)
            NSColor.clear.set()
            NSBezierPath(ovalIn: badge.insetBy(dx: -1.25, dy: -1.25)).fill(using: .copy)
            NSColor.systemRed.setFill()
            NSBezierPath(ovalIn: badge).fill()

            let attributes: [NSAttributedString.Key: Any] = [
                .font: NSFont.systemFont(ofSize: 7, weight: .heavy),
                .foregroundColor: NSColor.white,
            ]
            let mark = NSAttributedString(string: "!", attributes: attributes)
            let markSize = mark.size()
            mark.draw(at: NSPoint(x: badge.midX - markSize.width / 2, y: badge.midY - markSize.height / 2))
            return true
        }
        image.accessibilityDescription = "Locus, focus session active"
        return image
    }

    private static func symbol(_ name: String) -> NSImage? {
        let image = NSImage(systemSymbolName: name, accessibilityDescription: "Locus")
        image?.isTemplate = true
        return image
    }
}

private extension NSBezierPath {
    func fill(using operation: NSCompositingOperation) {
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current?.compositingOperation = operation
        fill()
        NSGraphicsContext.restoreGraphicsState()
    }
}
